- id: fmt
  name: cargo fmt
  description: Format files with cargo fmt.
  entry: cargo fmt
  language: rust
  types: [rust]
  files: \.rs$
  args: ["--"]
- id: check
  name: cargo check
  description: Check the package for errors.
  entry: cargo check
  language: rust
  types: [rust]
  files: \.rs$
  pass_filenames: false
- id: clippy
  name: cargo clippy
  description: Check for linting issues with cargo.
  entry: cargo clippy
  language: rust
  args: ["--"]
  types: [rust]
  files: \.rs$
  pass_filenames: false
